FROM hazibase

ENTRYPOINT ["bash", "-c", \
    "( chown root:root /home/dummy/info; chown dummy:dummy /home/dummy/*.* ) 2> /dev/null; \"$@\"", ""]
CMD ["timeout", "--kill-after=10s", "60s", "/HW/main"]

ADD HW /HW
RUN ["chmod", "-R", "550", "/HW/"]
