FROM hazibase

ENTRYPOINT chmod -R 550 /HW/ && \
            (chown root:root /home/dummy/info; chown dummy:dummy /home/dummy/*.*; true)2> /dev/null && \
           timeout --kill-after=10s 60s /HW/main

ADD HW /HW
