#!/bin/bash
# entrypoint for the docker
# don't use this script outside of the docker!

function timelimit
{
    timeout --kill-after=1s 55s "$@"
}

if [ ! -f /home/dummy/info ]
then
    /HW/log INVALID submission content \"`ls /home/dummy/`\"
    exit
fi

# is the sender valid?
SENDER=`head -n 1 /home/dummy/info`
SENDERINFO=`/HW/getsenderinfo "$SENDER"`

if [ $? -ne 0 ]
then
    /HW/log INVALID sender "\"$SENDER\""
    exit
fi

SUBJECT=`head -n 2 /home/dummy/info | tail -n 1`
RECIEVED=`head -n 3 /home/dummy/info | tail -n 1`

SOLUTIONS=`cd /home/dummy; ls -1 *.* 2> /dev/null | sed -e 's/\.[^.]\+$//' | sort | uniq`

# is it a submission at all?
if [ -z "$SOLUTIONS" ]
then
    /HW/off "$SENDERINFO"
    /HW/log INFO from "\"$SENDER\"" subject "\"$SUBJECT\""
    exit
fi

RESERVED_NAMES="off main getsenderinfo validate email log"

echo "$SOLUTIONS" | while read exercise
do
    if [ ! -f "/HW/$exercise/manifest.json" ]
    then
        # there is no such exercise!
        /HW/log INVALID from "\"$SENDER\"" non-existent exercise "\"$exercise\""
        /HW/email "$SENDER" "\"$exercise\"" "<span class=red>No such exercise!</span>"
        continue
    else
        # validate submission for this exercise
        VALIDATEINFO=`/HW/validate "$exercise" "$SENDERINFO"`
        if [ $? -ne 0 ]
        then
            /HW/log ERROR unable to validate submission from "\"$SENDER\"" exercise "\"$exercise\""
            /HW/email "$SENDER" "\"$exercise\"" "<span class=orange>Server error!</span> unable to validate!"
            continue
        fi
        TYPE=`head -n 1 <<<"$VALIDATEINFO"`
        if [[ ! -x "/HW/$TYPE" || " $RESERVED_NAMES " == *" $TYPE "* ]]
        then
            /HW/log ERROR exercise "\"$exercise\"" invalid type "\"$TYPE\""
            /HW/email "$SENDER" "\"$exercise\"" "<span class=orange>Server error!</span> Cannot evaluate exercise!"
            continue
        fi
        if [ "`head -n 2 <<<"$VALIDATEINFO" | tail -n 1`" = "reject" ]
        then
            /HW/log INVALID submission from "\"$SENDER\"" exercise "\"$exercise\""
            /HW/email "$SENDER" "\"$exercise\"" "<span class=red>Invalid submission!</span>"
            continue
        fi
        
        MESSAGE=$(timelimit "/HW/$TYPE" "$exercise")
        RESULT=$?

        if [ -z "`head -n 3 <<<"$VALIDATEINFO" | tail -n 1 | grep tests`" ]
        then
            MESSAGE=
        fi
        
        if [ "`head -n 3 <<<"$VALIDATEINFO" | tail -n 1 | grep description`" ]
        then
            MESSAGE="<h2>Description</h2>
<div class=description>
"`python3 -c "import json; manifest = json.load(open('/HW/$exercise/manifest.json', 'r', encoding='utf8')); print('' if 'description' not in manifest else manifest['description'])"`"
</div>
$MESSAGE"
        fi
        
        if [ $RESULT -eq 124 ]
        then
            RESULT=0
            MESSAGE="<p><span class=yellow>Your submission timed out!</span></p>
$MESSAGE"
        fi
        
        if [ "`head -n 3 <<<"$VALIDATEINFO" | tail -n 1 | grep score`" ]
        then
            MAXSCORE=`head -n 4 <<<"$VALIDATEINFO" | tail -n 1`
            if [ "$MAXSCORE" -a `wc -l <<<"$VALIDATEINFO"` -gt 3 ]
            then
                MESSAGE="<h1 class=score>Score: $RESULT out of $MAXSCORE</h1>
$MESSAGE"
            else
                MESSAGE="<h1 class=score>Score: $RESULT</h1>
$MESSAGE"
            fi
        fi

        if [ "`head -n 2 <<<"$VALIDATEINFO" | tail -n 1`" != "valid" ]
        then
            /HW/log INVALID submission from "\"$SENDER\"" exercise "\"$exercise\"" returned $RESULT
            MESSAGE="<p><span class=yellow>Invalid submission!</span></p>
$MESSAGE"
        else
            /HW/log "<SUCCESS>" submission from "\"$SENDER\"" exercise "\"$exercise\"" returned $RESULT
        fi
        if [ -z "$MESSAGE" ]
        then
            /HW/email "$SENDER" "\"$exercise\"" "Acknowledged!"
        else
            /HW/email "$SENDER" "\"$exercise\"" "$MESSAGE"
        fi
    fi
done
