name: Update Hash
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Hash
      run: bash generate_readme.sh > README.md
    - name: Commit readme
      run: |
        git add README.md
        if [ ! "`git status --short README.md`" ]; then exit 0; fi
        git config --global user.name 'Bot of github.com/gaebor/hazi'
        git config --global user.email 'bot-of-gaebor-hazi@users.noreply.github.com'
        git commit -m "update hash of commit `git log -n 1 --pretty=format:%H` in readme" README.md
        git push
 